apiVersion: retail.ecommerce/v1alpha1
kind: Domain
metadata:
  name: engagement
spec:
  status: planned
  businessOwner: TODO
  technicalOwner: TODO
  services: []
  dataProducts: []
  support:
    channel: TODO
    runbook: TODO
